// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVA0rC97RZpI3J6f462HWel2dONcTLcNg',
    appId: '1:233399845754:web:8f39906dffc5c72b8d4cc3',
    messagingSenderId: '233399845754',
    projectId: 'lyricstream-403e0',
    authDomain: 'lyricstream-403e0.firebaseapp.com',
    storageBucket: 'lyricstream-403e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrhvL1B8RDO_c0JO-FPS0-3p9iMrlDu8',
    appId: '1:233399845754:android:7272b3938e0e8c0f8d4cc3',
    messagingSenderId: '233399845754',
    projectId: 'lyricstream-403e0',
    storageBucket: 'lyricstream-403e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi1SdQWxy_DntBuP2fyZlFAzoha6vBBfA',
    appId: '1:233399845754:ios:f15b8352d38a1ee68d4cc3',
    messagingSenderId: '233399845754',
    projectId: 'lyricstream-403e0',
    storageBucket: 'lyricstream-403e0.firebasestorage.app',
    iosBundleId: 'com.example.lyricStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi1SdQWxy_DntBuP2fyZlFAzoha6vBBfA',
    appId: '1:233399845754:ios:f15b8352d38a1ee68d4cc3',
    messagingSenderId: '233399845754',
    projectId: 'lyricstream-403e0',
    storageBucket: 'lyricstream-403e0.firebasestorage.app',
    iosBundleId: 'com.example.lyricStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVA0rC97RZpI3J6f462HWel2dONcTLcNg',
    appId: '1:233399845754:web:95ec0593382a897f8d4cc3',
    messagingSenderId: '233399845754',
    projectId: 'lyricstream-403e0',
    authDomain: 'lyricstream-403e0.firebaseapp.com',
    storageBucket: 'lyricstream-403e0.firebasestorage.app',
  );
}
